name = "dtlogs"
main = "src/worker.js"
compatibility_date = "2025-08-29"
account_id = "7febaff00764d1a1d9b4ebb8b095df51"

[triggers]
crons = ["0 0 * * *"]  # KST 09:00

[[d1_databases]]
binding = "DB"
database_name = "dtlogs-db"
database_id = "0614bd30-1c0b-40a2-98de-34efa2b54247"

[vars]
ALLOWED_SITES = "engineering.atspotify.com,dropbox.tech,slack.engineering,stripe.com,developer.apple.com,netflixtechblog.com,engineering.fb.com,developers.googleblog.com"
DAYS_LIMIT = "1460"
LANG_THRESHOLD = "0.9"
